export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as Landing } from './Landing/Landing'
export { default as About } from './About/About'
export { default as Tools } from './Tools/Tools'
export { default as Education } from './Education/Education'
export { default as Experience } from'./Experience/Experience'
export { default as Contacts } from'./Contacts/Contacts'
export { default as GroupProjects } from './GroupProjects/GroupProjects'
export { default as PersonalProjects } from './PersonalProjects/PersonalProjects'
export { default as SingleProject } from './GroupProjects/SingleProject/SingleGroupProject'
export { default as Skills } from "./Skills/Skills"